### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by baliestri** [SouJunior/linkedin-backend#15]
Me surgiram algumas dúvidas após ver o projeto:

1. Porque não está sendo utilizado Typescript?
2. Porque não está sendo utilizado Nest.js + (Express.js ou Fastify)?
3. Porque está tudo em português (arquivos, variáveis, funções)?

**Comment by brenodanyel** [comment]
Sobre os pontos 1 e 2: Se for por falta de "mão de obra" pra fazer a migração, eu mesmo me disponho a subir um PR com as mudanças sugeridas, só falar ;)
