### ISSUE TITLE
Crud - Vagas simples

### ISSUE THREAD

**Issue by wouerner** [SouJunior/linkedin-backend#2]
O usuário gostaria de entrar no sistema deslogado e cadastrar vagas, visualizar, editar e apagar essa vaga, com os dados:

- Titulo da vaga
- descrição
- Tipo: Estagio, Trainee ou Junior

**Comment by LarissaSNascimento** [comment]
- O Crud (Tarefa) está pronto, mas falta conectar com o Banco de Dados que ainda está em fase de desenvolvimento.

**Comment by AdamTeodoro** [comment]
Posso ajudar testando o código de vocês ? S2

**Comment by LeonardoReis86** [comment]
Banco de dados conectado ao CRUD
