### ISSUE TITLE
Criar a paginação

### ISSUE THREAD

**Issue by mandyfontes** [SouJunior/linkedin-backend#43]

**Comment by BeatrizFFranco** [comment]
@wandersonDeve favor poderia detalhar o card para que possamos entender e executar os testes?

**Comment by wandersonDeve** [comment]
Paginação das Companies.

Endpoint de buscar todas as companies com paginação.

Envia na query alguns parametros 
![image](https://user-images.githubusercontent.com/81826043/224856542-b923201c-d630-46a0-a7d4-9a7359bf07e8.png)
 Onde:
  - orderByColumn - É a ordenação por alguma coluna (por padrao ela pega ID)
  - page - É o numero da pagina
  - take - Quantidade de itens por pagina
  - order - ASC (Crescente) ou DESC (Decrescente)
  
  Apos o envio desses dados terá o retorno dos dados das companies mais um campo chamado meta, que irá conter as informações da paginação.
  
  
![image](https://user-images.githubusercontent.com/81826043/224856807-87ed8335-bb5c-4eae-a7f5-b417c2a1513d.png)

Onde:
   - itemCount - Quantos itens tem ao todo
   - pageCount - Quantas paginas existe ao todo
   - hasPreviousPage - Retorna `true` ou `false` , (Existe uma pagina anterior)
   - hasNextPage - Retorna `true` ou `false` , (Existe uma pagina depois)
