### ISSUE TITLE
Banco de dados Backend

### ISSUE THREAD

**Issue by wouerner** [SouJunior/linkedin-backend#7]
- Docker
- Docker compose
- Instruções para uso, se necessario video.
- Postgres

**Comment by LarissaSNascimento** [comment]
Fazer nivelamento sobre o uso da tecnologia Docker.

**Comment by wandersonDeve** [comment]
![Image](https://user-images.githubusercontent.com/81826043/191883406-ebe52685-069b-423d-a43d-d661a4e410f4.png)
